### ISSUE TITLE
ModuleNotFoundError: No module named 'instance'

### ISSUE THREAD

**Issue by dashuaip** [garg-akash-elibot/cs_elibot#1]
我在Ubuntu20.04 ROS noetic运行时出现了这个问题，请问应该怎么解决？

```
process[cs_driver-2]: started with pid [3625]
Traceback (most recent call last):
  File "/home/jh/catkin_ws/devel/lib/cs_driver/cs_driver_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/jh/catkin_ws/src/cs_elibot/cs_driver/scripts/cs_driver_node.py", line 2, in <module>
    from cs_driver.cs_driver import CSDriver
  File "/home/jh/catkin_ws/src/cs_elibot/cs_driver/src/cs_driver/cs_driver.py", line 3, in <module>
    from cs_driver.get_joint_position_server import GetJointPositionService
  File "/home/jh/catkin_ws/src/cs_elibot/cs_driver/src/cs_driver/get_joint_position_server.py", line 4, in <module>
    import instance as instance
ModuleNotFoundError: No module named 'instance'
[cs_driver-2] process has died [pid 3625, exit code 1, cmd /home/jh/catkin_ws/devel/lib/cs_driver/cs_driver_node.py __name:=cs_driver __log:=/home/jh/.ros/log/b4978b20-3541-11ef-a4fb-4146dfe0aedf/cs_driver-2.log].
log file: /home/jh/.ros/log/b4978b20-3541-11ef-a4fb-4146dfe0aedf/cs_driver-2*.log
```

**Comment by dashuaip** [comment]
Python 版本为3.8
